#!/bin/bash

#cd ~/final/P400-T15

#for j in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
#cd $j
#~/final/scripts/pegs_output_to_pwscf.sh pegs.out Na Cl >pw.in$j
#cd ..
#done


for i in 11 12 13 14 15 16 17 18 19 20; do
cp ~/final/P400-T15/$i/pw.in$i ~/final/part1/
done

#cd ~/final/P400-T15
#for j in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
#cd $j
#touch "struc""$j"
#~/final/scripts/pegs_output_to_vasp.sh  pegs.out Na Cl > struc$j
#echo "dsdhhjfhj"
#cd ..
#done
#module load intel/2016.0 
#cd ~/final/P400-T15
#for j in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
#cd $j
#echo "this id structure of ""$j"
#echo " structure of 5" > relaxedstr
#~/final/scripts/mint/mint  srtpw5 -conventional -about -tol 0.2 >> relaxedstr
#cd ..
#done
