! Generated by using cif2qe Version 1.2 - Date: Sun Mar 18 13:17:15 CDT 2018
!   _symmetry_space_group_name_H-M = 
!   _symmetry_Int_Tables_number = 1
!   _symmetry_cell_setting = 
! a=4.02464  b=4.02464  c=4.02464  alpha=60  beta=60  gamma=60
! Found by cif2qe: lattice = rhombohedral    Space group = P1   ibrav = 4
!
!
! Symmetry found:
!   1                        x, y, z    [x]  [ y]  [ z]
&CONTROL
                       title = 'cF8-NaCl-prototype.cif'
                 calculation = 'relax'
                restart_mode = 'from_scratch'
                      outdir = './1'
                  pseudo_dir = '../PP/atompaw'
                      prefix = 'cF8-NaCl-prototype'
                     disk_io = 'none'
                   verbosity = 'default'
               etot_conv_thr = 0.0001
               forc_conv_thr = 0.001
                       nstep = 400
                     tstress = .true.
                     tprnfor = .true.
 /
 &SYSTEM
                       ibrav = 0
                         nat = 2
                        ntyp = 2
                     ecutwfc = 60
                     ecutrho = 480
                    vdw_corr = 'xdm'
                      xdm_a1 = 1.2153
                      xdm_a2 = 2.3704
 /
 &ELECTRONS
            electron_maxstep = 200
                    conv_thr = 1.0D-7
              diago_thr_init = 1e-4
                 startingpot = 'atomic'
                 startingwfc = 'atomic'
                 mixing_mode = 'plain'
                 mixing_beta = 0.5
                 mixing_ndim = 8
             diagonalization = 'david'
 /
&IONS
                ion_dynamics = 'bfgs'
 /

ATOMIC_SPECIES
   Na   22.9897000000  Na.pw86pbe-n-kjpaw_psl.1.0.0.UPF
   Cl   35.4530000000  Cl.pw86pbe-n-kjpaw_psl.1.0.0.UPF

ATOMIC_POSITIONS crystal
Na      0.00000000000000      0.00000000000000      0.00000000000000
Cl      0.50000000000000      0.50000000000000      0.50000000000000

K_POINTS automatic
4  4  4   0 0 0

CELL_PARAMETERS
     7.60545812810604      0.00000000000000      0.00000000000000
     3.80272906405302      6.58651994635868      0.00000000000000
     3.80272906405302      2.19550664878623      6.20983055798757



