! Generated by using cif2qe Version 1.2 - Date: Sun Mar 18 13:17:16 CDT 2018
!   _symmetry_space_group_name_H-M = 
!   _symmetry_Int_Tables_number = 1
!   _symmetry_cell_setting = 
! a=3.77391  b=3.77391  c=3.77391  alpha=90  beta=90  gamma=90
! Found by cif2qe: lattice = cubic    Space group = P1   ibrav = 1
!
!
! Symmetry found:
!   1                        x, y, z    [x]  [ y]  [ z]
&CONTROL
                       title = 'cP4-Cu3Au-prototype.cif'
                 calculation = 'relax'
                restart_mode = 'from_scratch'
                      outdir = './1'
                  pseudo_dir = '../PP/atompaw'
                      prefix = 'cP4-Cu3Au-prototype'
                     disk_io = 'none'
                   verbosity = 'default'
               etot_conv_thr = 0.0001
               forc_conv_thr = 0.001
                       nstep = 400
                     tstress = .true.
                     tprnfor = .true.
 /
 &SYSTEM
                       ibrav = 0
                         nat = 4
                        ntyp = 2
                     ecutwfc = 60
                     ecutrho = 480
                    vdw_corr = 'xdm'
                      xdm_a1 = 1.2153
                      xdm_a2 = 2.3704
 /
 &ELECTRONS
            electron_maxstep = 200
                    conv_thr = 1.0D-7
              diago_thr_init = 1e-4
                 startingpot = 'atomic'
                 startingwfc = 'atomic'
                 mixing_mode = 'plain'
                 mixing_beta = 0.5
                 mixing_ndim = 8
             diagonalization = 'david'
 /
&IONS
                ion_dynamics = 'bfgs'
 /

ATOMIC_SPECIES
   Cu   63.5460000000  Cu.pw86pbe-n-kjpaw_psl.1.0.0.UPF
   Au  196.9660000000  Au.pw86pbe-n-kjpaw_psl.1.0.0.UPF

ATOMIC_POSITIONS crystal
Cu      0.00000000000000      0.50000000000000      0.50000000000000
Cu      0.50000000000000      0.50000000000000      0.00000000000000
Cu      0.50000000000000      0.00000000000000      0.50000000000000
Au      0.00000000000000      0.00000000000000      0.00000000000000

K_POINTS automatic
4  4  4   0 0 0

CELL_PARAMETERS
     7.13166486031942      0.00000000000000      0.00000000000000
     0.00000000000000      7.13166486031942      0.00000000000000
     0.00000000000000      0.00000000000000      7.13166486031942



