! Generated by using cif2qe Version 1.2 - Date: Sun Mar 18 13:17:16 CDT 2018
!   _symmetry_space_group_name_H-M = 
!   _symmetry_Int_Tables_number = 1
!   _symmetry_cell_setting = 
! a=6.80164  b=6.80164  c=6.80164  alpha=134.15  beta=105.479  gamma=92.096
! Found by cif2qe: lattice = triclinic    Space group = P1   ibrav = 14
!
!
! Symmetry found:
!   1                        x, y, z    [x]  [ y]  [ z]
&CONTROL
                       title = 'oI12-KHg2-prototype.cif'
                 calculation = 'relax'
                restart_mode = 'from_scratch'
                      outdir = './1'
                  pseudo_dir = '../PP/atompaw'
                      prefix = 'oI12-KHg2-prototype'
                     disk_io = 'none'
                   verbosity = 'default'
               etot_conv_thr = 0.0001
               forc_conv_thr = 0.001
                       nstep = 400
                     tstress = .true.
                     tprnfor = .true.
 /
 &SYSTEM
                       ibrav = 0
                         nat = 6
                        ntyp = 2
                     ecutwfc = 60
                     ecutrho = 480
                    vdw_corr = 'xdm'
                      xdm_a1 = 1.2153
                      xdm_a2 = 2.3704
 /
 &ELECTRONS
            electron_maxstep = 200
                    conv_thr = 1.0D-7
              diago_thr_init = 1e-4
                 startingpot = 'atomic'
                 startingwfc = 'atomic'
                 mixing_mode = 'plain'
                 mixing_beta = 0.5
                 mixing_ndim = 8
             diagonalization = 'david'
 /
&IONS
                ion_dynamics = 'bfgs'
 /

ATOMIC_SPECIES
    K   39.0983000000  K.pw86pbe-n-kjpaw_psl.1.0.0.UPF
   Hg  200.5900000000  Hg.pw86pbe-n-kjpaw_psl.1.0.0.UPF

ATOMIC_POSITIONS crystal
 K      0.20086200000000      0.95086200000000      0.75000000000000
 K      0.79913800000000      0.04913800000000      0.25000000000000
Hg      0.39110700000000      0.33699000000000      0.55411700000000
Hg      0.60889300000000      0.66301000000000      0.44588300000000
Hg      0.78287400000000      0.33699000000000      0.94588300000000
Hg      0.21712600000000      0.66301000000000      0.05411700000000

K_POINTS automatic
2  2  2   0 0 0

CELL_PARAMETERS
    12.85322937126304      0.00000000000000      0.00000000000000
    -0.47008766754743     12.84463011748951      0.00000000000000
    -3.43030788016959     -9.08436996689738      8.42096879355802



