! Generated by using cif2qe Version 1.2 - Date: Sun Mar 18 13:17:16 CDT 2018
!   _symmetry_space_group_name_H-M = 
!   _symmetry_Int_Tables_number = 1
!   _symmetry_cell_setting = 
! a=3.71223  b=4.88516  c=7.0459  alpha=90  beta=90  gamma=90
! Found by cif2qe: lattice = orthorhombic    Space group = P1   ibrav = 8
!
!
! Symmetry found:
!   1                        x, y, z    [x]  [ y]  [ z]
&CONTROL
                       title = 'oP12-Co2Si-prototype.cif'
                 calculation = 'relax'
                restart_mode = 'from_scratch'
                      outdir = './1'
                  pseudo_dir = '../PP/atompaw'
                      prefix = 'oP12-Co2Si-prototype'
                     disk_io = 'none'
                   verbosity = 'default'
               etot_conv_thr = 0.0001
               forc_conv_thr = 0.001
                       nstep = 400
                     tstress = .true.
                     tprnfor = .true.
 /
 &SYSTEM
                       ibrav = 0
                         nat = 12
                        ntyp = 2
                     ecutwfc = 60
                     ecutrho = 480
                    vdw_corr = 'xdm'
                      xdm_a1 = 1.2153
                      xdm_a2 = 2.3704
 /
 &ELECTRONS
            electron_maxstep = 200
                    conv_thr = 1.0D-7
              diago_thr_init = 1e-4
                 startingpot = 'atomic'
                 startingwfc = 'atomic'
                 mixing_mode = 'plain'
                 mixing_beta = 0.5
                 mixing_ndim = 8
             diagonalization = 'david'
 /
&IONS
                ion_dynamics = 'bfgs'
 /

ATOMIC_SPECIES
   Co   58.9332000000  Co.pw86pbe-n-kjpaw_psl.1.0.0.UPF
   Si   28.0855000000  Si.pw86pbe-n-kjpaw_psl.1.0.0.UPF

ATOMIC_POSITIONS crystal
Co      0.75000000000000      0.82640100000000      0.43573600000000
Co      0.25000000000000      0.17359900000000      0.56426400000000
Co      0.75000000000000      0.32640100000000      0.06426400000000
Co      0.25000000000000      0.67359900000000      0.93573600000000
Co      0.25000000000000      0.53708600000000      0.28234500000000
Co      0.75000000000000      0.46291400000000      0.71765500000000
Co      0.25000000000000      0.03708600000000      0.21765500000000
Co      0.75000000000000      0.96291400000000      0.78234500000000
Si      0.25000000000000      0.20285400000000      0.89360000000000
Si      0.75000000000000      0.79714600000000      0.10640000000000
Si      0.25000000000000      0.70285400000000      0.60640000000000
Si      0.75000000000000      0.29714600000000      0.39360000000000

K_POINTS automatic
4  3  2   0 0 0

CELL_PARAMETERS
     7.01510507896987      0.00000000000000      0.00000000000000
     0.00000000000000      9.23162140997514      0.00000000000000
     0.00000000000000      0.00000000000000     13.31481257053827



