! Generated by using cif2qe Version 1.2 - Date: Sun Mar 18 13:17:15 CDT 2018
!   _symmetry_space_group_name_H-M = 
!   _symmetry_Int_Tables_number = 1
!   _symmetry_cell_setting = 
! a=4.65716  b=5.0473  c=7.04133  alpha=90  beta=90  gamma=90
! Found by cif2qe: lattice = orthorhombic    Space group = P1   ibrav = 8
!
!
! Symmetry found:
!   1                        x, y, z    [x]  [ y]  [ z]
&CONTROL
                       title = 'oP16-Fe3C-prototype.cif'
                 calculation = 'relax'
                restart_mode = 'from_scratch'
                      outdir = './1'
                  pseudo_dir = '../PP/atompaw'
                      prefix = 'oP16-Fe3C-prototype'
                     disk_io = 'none'
                   verbosity = 'default'
               etot_conv_thr = 0.0001
               forc_conv_thr = 0.001
                       nstep = 400
                     tstress = .true.
                     tprnfor = .true.
 /
 &SYSTEM
                       ibrav = 0
                         nat = 16
                        ntyp = 2
                     ecutwfc = 60
                     ecutrho = 480
                    vdw_corr = 'xdm'
                      xdm_a1 = 1.2153
                      xdm_a2 = 2.3704
 /
 &ELECTRONS
            electron_maxstep = 200
                    conv_thr = 1.0D-7
              diago_thr_init = 1e-4
                 startingpot = 'atomic'
                 startingwfc = 'atomic'
                 mixing_mode = 'plain'
                 mixing_beta = 0.5
                 mixing_ndim = 8
             diagonalization = 'david'
 /
&IONS
                ion_dynamics = 'bfgs'
 /

ATOMIC_SPECIES
   Fe   55.8450000000  Fe.pw86pbe-n-kjpaw_psl.1.0.0.UPF
    C   12.0107000000  C.pw86pbe-n-kjpaw_psl.1.0.0.UPF

ATOMIC_POSITIONS crystal
Fe      0.34729400000000      0.16863600000000      0.92247800000000
Fe      0.15270600000000      0.66863600000000      0.57752200000000
Fe      0.84729400000000      0.33136400000000      0.42247800000000
Fe      0.33966400000000      0.45020900000000      0.25000000000000
Fe      0.15270600000000      0.66863600000000      0.92247800000000
Fe      0.34729400000000      0.16863600000000      0.57752200000000
Fe      0.16033600000000      0.95020900000000      0.25000000000000
Fe      0.65270600000000      0.83136400000000      0.42247800000000
Fe      0.84729400000000      0.33136400000000      0.07752200000000
Fe      0.66033600000000      0.54979100000000      0.75000000000000
Fe      0.65270600000000      0.83136400000000      0.07752200000000
Fe      0.83966400000000      0.04979100000000      0.75000000000000
 C      0.00000000000000      0.00000000000000      0.00000000000000
 C      0.50000000000000      0.50000000000000      0.00000000000000
 C      0.50000000000000      0.50000000000000      0.50000000000000
 C      0.00000000000000      0.00000000000000      0.50000000000000

K_POINTS automatic
3  3  2   0 0 0

CELL_PARAMETERS
     8.80076498740998      0.00000000000000      0.00000000000000
     0.00000000000000      9.53801510315425      0.00000000000000
     0.00000000000000      0.00000000000000     13.30618349523841



