! Generated by using cif2qe Version 1.2 - Date: Sun Mar 18 13:17:15 CDT 2018
!   _symmetry_space_group_name_H-M = 
!   _symmetry_Int_Tables_number = 1
!   _symmetry_cell_setting = 
! a=7.08726  b=7.08726  c=5.3078  alpha=90  beta=90  gamma=140.924
! Found by cif2qe: lattice = triclinic    Space group = P1   ibrav = 14
!
!
! Symmetry found:
!   1                        x, y, z    [x]  [ y]  [ z]
&CONTROL
                       title = 'oS8-TlI-prototype.cif'
                 calculation = 'relax'
                restart_mode = 'from_scratch'
                      outdir = './1'
                  pseudo_dir = '../PP/atompaw'
                      prefix = 'oS8-TlI-prototype'
                     disk_io = 'none'
                   verbosity = 'default'
               etot_conv_thr = 0.0001
               forc_conv_thr = 0.001
                       nstep = 400
                     tstress = .true.
                     tprnfor = .true.
 /
 &SYSTEM
                       ibrav = 0
                         nat = 4
                        ntyp = 2
                     ecutwfc = 60
                     ecutrho = 480
                    vdw_corr = 'xdm'
                      xdm_a1 = 1.2153
                      xdm_a2 = 2.3704
 /
 &ELECTRONS
            electron_maxstep = 200
                    conv_thr = 1.0D-7
              diago_thr_init = 1e-4
                 startingpot = 'atomic'
                 startingwfc = 'atomic'
                 mixing_mode = 'plain'
                 mixing_beta = 0.5
                 mixing_ndim = 8
             diagonalization = 'david'
 /
&IONS
                ion_dynamics = 'bfgs'
 /

ATOMIC_SPECIES
   Tl  204.3830000000  Tl.pw86pbe-n-kjpaw_psl.1.0.0.UPF
    I  126.9040000000  I.pw86pbe-n-kjpaw_psl.1.0.0.UPF

ATOMIC_POSITIONS crystal
Tl      0.38601300000000      0.61398700000000      0.75000000000000
Tl      0.61398700000000      0.38601300000000      0.25000000000000
 I      0.13258400000000      0.86741600000000      0.75000000000000
 I      0.86741600000000      0.13258400000000      0.25000000000000

K_POINTS automatic
2  2  3   0 0 0

CELL_PARAMETERS
    13.39297219107086      0.00000000000000      0.00000000000000
   -10.39710828727534      8.44226529869015      0.00000000000000
     0.00000000000000      0.00000000000000     10.03029452226812



